apiVersion: v1
kind: Service
metadata:
  name: cadastro-api
  labels:
    app: cadastro-api
spec:
  selector:
    app: cadastro-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5141
  type: ClusterIP
