apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: inclusao-monitor
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: inclusao
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
