apiVersion: v1
kind: Service
metadata:
  name: inclusao
  labels:
    app: inclusao
spec:
  selector:
    app: inclusao
  ports:
    - name: http
      port: 9097
      targetPort: 9097
  type: ClusterIP
