apiVersion: apps/v1
kind: Deployment
metadata:
  name: atualizacao-worker
  labels:
    app: atualizacao-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atualizacao-worker
  template:
    metadata:
      labels:
        app: atualizacao-worker
    spec:
      containers:
        - name: atualizacao-worker
          image: seu-usuario-dockerhub/atualizacao-worker:latest
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: RabbitMq__Host
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RabbitMqHost
            - name: RabbitMq__Port
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RabbitMqPort
