apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: atualizacao-monitor
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: atualizacao
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
