apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-api
  labels:
    app: gateway-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-api
  template:
    metadata:
      labels:
        app: gateway-api
    spec:
      containers:
        - name: gateway-api
          image: seu-usuario-dockerhub/gateway-api:latest
          ports:
            - containerPort: 5149
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
