apiVersion: v1
kind: Service
metadata:
  name: gateway-api
  labels:
    app: gateway-api
spec:
  selector:
    app: gateway-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5149
  type: ClusterIP
