apiVersion: v1
kind: Service
metadata:
  name: remocao
  labels:
    app: remocao
spec:
  selector:
    app: remocao
  ports:
    - name: http
      port: 9097
      targetPort: 9097
  type: ClusterIP
